# -*- coding: utf-8 -*-
"""Personal_financial_advisor

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11mw5pi35Ls7WFi9Sg70I3Ak08GPNlj6m
"""

import pandas as pd
import streamlit as st

st.title("💰 Personal Finance Advisor")

import pandas as pd

# Personal Finance Advisor

# Step 1: Load Dataset
# The first row of this raw DataFrame contains the actual header string
header_string = df_raw.iloc[0, 0] # e.g., 'date,category,amount,payment_mode,description'
column_names = header_string.split(',') # ['date', 'category', 'amount', 'payment_mode', 'description']

# The rest of the rows contain the data, also as single comma-separated strings
data_rows = df_raw.iloc[1:, 0]

# Split each data string into columns
df = data_rows.str.split(',', expand=True)
df.columns = column_names # Assign the extracted column names

# Convert 'amount' to numeric, as it will be strings after splitting
df['amount'] = pd.to_numeric(df['amount'])

print("Dataset Loaded ✔️")
print("DataFrame Columns:", df.columns)
print("DataFrame Head:\n", df.head())
df.describe()

# Step 2: Total Spending
total_spend = df['amount'].sum()
print("Total Spending: $", total_spend)

# Step 3: Category-wise Analysis
category_spend = df.groupby('category')['amount'].sum()
print("Total Spending by Category:\n", category_spend)

# Step 4: Sort Spending
category_spend_sorted = category_spend.sort_values(ascending=False)
print('Category spend sorted', category_spend_sorted)

# Step 5: Generate Insights

# Highest spending category
highest_category = category_spend.idxmax()

print("\n--- Insights ---")
print("You spend the most on:", highest_category)

# Suggestion
if highest_category == "Shopping":
    print("Try to reduce shopping expenses.")
elif highest_category == "Food":
    print("Try to spend less on outside food.")
elif highest_category == "Entertainment":
    print("Reduce entertainment expenses.")
else:
    print("Try to control your spending.")

# Budget check
budget = 5000

if total > budget:
    print("You are over your budget.")
else:
    print("You are within your budget.")